slack:
  bot:
    channel: the_legend_of_zealda
    name: zealda

logging:
  level:
    com.pink: DEBUG
    com.ullink.slack: INFO

jobdetails:
  quest:
    assignment:
      defaultMessage: "Thou have a new quest to accomplish."
      time: "10 * * ? * MON,TUE,WED,THU,FRI *"
